"""Initial schema V2

Revision ID: 10cb51a78470
Revises: 
Create Date: 2026-01-22 21:57:38.012107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cb51a78470'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('button_config', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_bots_id'), 'bots', ['id'], unique=False)
    op.create_table('license_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_by_group', sa.BigInteger(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_codes_code'), 'license_codes', ['code'], unique=True)
    op.create_index(op.f('ix_license_codes_id'), 'license_codes', ['id'], unique=False)
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_group_id'), 'operators', ['group_id'], unique=False)
    op.create_index(op.f('ix_operators_id'), 'operators', ['id'], unique=False)
    op.create_table('bot_exchange_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('usd_rate', sa.Float(), nullable=True),
    sa.Column('php_rate', sa.Float(), nullable=True),
    sa.Column('myr_rate', sa.Float(), nullable=True),
    sa.Column('thb_rate', sa.Float(), nullable=True),
    sa.Column('decimal_mode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id')
    )
    op.create_index(op.f('ix_bot_exchange_templates_id'), 'bot_exchange_templates', ['id'], unique=False)
    op.create_table('bot_fee_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('fee_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id')
    )
    op.create_index(op.f('ix_bot_fee_templates_id'), 'bot_fee_templates', ['id'], unique=False)
    op.create_table('group_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('active_start_time', sa.DateTime(), nullable=True),
    sa.Column('fee_percent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('usd_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('php_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('myr_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('thb_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('decimal_mode', sa.Boolean(), nullable=True),
    sa.Column('simple_mode', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('license_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_configs_group_id'), 'group_configs', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_configs_id'), 'group_configs', ['id'], unique=False)
    op.create_table('ledger_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('operator_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('fee_applied', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('usd_rate_snapshot', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('original_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_records_group_id'), 'ledger_records', ['group_id'], unique=False)
    op.create_index(op.f('ix_ledger_records_id'), 'ledger_records', ['id'], unique=False)
    op.create_table('trial_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_requests_id'), 'trial_requests', ['id'], unique=False)
    op.create_index(op.f('ix_trial_requests_user_id'), 'trial_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trial_requests_user_id'), table_name='trial_requests')
    op.drop_index(op.f('ix_trial_requests_id'), table_name='trial_requests')
    op.drop_table('trial_requests')
    op.drop_index(op.f('ix_ledger_records_id'), table_name='ledger_records')
    op.drop_index(op.f('ix_ledger_records_group_id'), table_name='ledger_records')
    op.drop_table('ledger_records')
    op.drop_index(op.f('ix_group_configs_id'), table_name='group_configs')
    op.drop_index(op.f('ix_group_configs_group_id'), table_name='group_configs')
    op.drop_table('group_configs')
    op.drop_index(op.f('ix_bot_fee_templates_id'), table_name='bot_fee_templates')
    op.drop_table('bot_fee_templates')
    op.drop_index(op.f('ix_bot_exchange_templates_id'), table_name='bot_exchange_templates')
    op.drop_table('bot_exchange_templates')
    op.drop_index(op.f('ix_operators_id'), table_name='operators')
    op.drop_index(op.f('ix_operators_group_id'), table_name='operators')
    op.drop_table('operators')
    op.drop_index(op.f('ix_license_codes_id'), table_name='license_codes')
    op.drop_index(op.f('ix_license_codes_code'), table_name='license_codes')
    op.drop_table('license_codes')
    op.drop_index(op.f('ix_bots_id'), table_name='bots')
    op.drop_table('bots')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
