"""Add bot_id to group categories

Revision ID: 58f19fb6466f
Revises: ea26bbecbe68
Create Date: 2026-01-25 19:59:50.407266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f19fb6466f'
down_revision: Union[str, None] = 'ea26bbecbe68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_id', sa.Integer(), nullable=True))
        batch_op.drop_index(op.f('ix_group_categories_name'))
        batch_op.create_index(op.f('ix_group_categories_name'), ['name'], unique=False)
        batch_op.create_foreign_key('fk_group_categories_bot_id', 'bots', ['bot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_group_categories_bot_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_group_categories_name'))
        batch_op.create_index(op.f('ix_group_categories_name'), ['name'], unique=True)
        batch_op.drop_column('bot_id')
    # ### end Alembic commands ###
