"""Initial migration

Revision ID: 931c64e8cf67
Revises: 
Create Date: 2026-01-22 21:42:20.472467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '931c64e8cf67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_group_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.alter_column('bots', 'button_config',
               existing_type=sqlite.JSON(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('group_configs', 'fee_percent',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('group_configs', 'usd_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('group_configs', 'php_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('group_configs', 'myr_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('group_configs', 'thb_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('group_configs', 'expire_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('ledger_records', 'amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('ledger_records', 'fee_applied',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('ledger_records', 'usd_rate_snapshot',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ledger_records', 'usd_rate_snapshot',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('ledger_records', 'fee_applied',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('ledger_records', 'amount',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('group_configs', 'expire_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('group_configs', 'thb_rate',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('group_configs', 'myr_rate',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('group_configs', 'php_rate',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('group_configs', 'usd_rate',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('group_configs', 'fee_percent',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('bots', 'button_config',
               existing_type=sa.String(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bot_id', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.VARCHAR(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_group_id'), 'transactions', ['group_id'], unique=False)
    # ### end Alembic commands ###
