"""add web_username to bots

Revision ID: a24c260d69e6
Revises: 58f19fb6466f
Create Date: 2026-04-11 16:52:23.142800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24c260d69e6'
down_revision: Union[str, None] = '58f19fb6466f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('web_username', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_bots_web_username', ['web_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bots_web_username', type_='unique')
        batch_op.drop_column('web_username')
    # ### end Alembic commands ###
