"""add group categories

Revision ID: d50b8282f1eb
Revises: 10cb51a78470
Create Date: 2026-01-25 14:12:29.589399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50b8282f1eb'
down_revision: Union[str, None] = '10cb51a78470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_categories_id'), 'group_categories', ['id'], unique=False)
    op.create_index(op.f('ix_group_categories_name'), 'group_categories', ['name'], unique=True)
    op.create_table('group_category_association',
    sa.Column('group_config_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['group_categories.id'], ),
    sa.ForeignKeyConstraint(['group_config_id'], ['group_configs.id'], ),
    sa.PrimaryKeyConstraint('group_config_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_category_association')
    op.drop_index(op.f('ix_group_categories_name'), table_name='group_categories')
    op.drop_index(op.f('ix_group_categories_id'), table_name='group_categories')
    op.drop_table('group_categories')
    # ### end Alembic commands ###
