"""add_bot_web_password

Revision ID: ea26bbecbe68
Revises: d50b8282f1eb
Create Date: 2026-01-25 18:19:42.767063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea26bbecbe68'
down_revision: Union[str, None] = 'd50b8282f1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('web_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'web_password')
    # ### end Alembic commands ###
